apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-demo
  labels:
    app: portfolio-demo
spec:
  selector:
    matchLabels:
      app: portfolio-demo
  template:
    metadata:
      labels:
        app: portfolio-demo
    spec:
      initContainers:
        - name: init-app
          image: hobord/invst-portfolio:demo
          env:
          - name: PORT
            value: "8080"
          - name: DB_HOST
            value: "mysql:3306"
          - name: DB_USER
            value: "dbuser"
          - name: DB_PASSWORD
            value: "secret"
          - name: DB_NAME
            value: "testdbs"
          - name: MIGRATIONS
            value: "/app/migrations"
          command:
            - bash
            - "-c"
            - /app/portfolio-server migrate
      containers:
      - name: backend
        resources: {}
        image: hobord/invst-portfolio:demo
        command:
            - bash
            - "-c"
            - /app/portfolio-server serve
        env:
          - name: PORT
            value: "8080"
          - name: DB_HOST
            value: "mysql:3306"
          - name: DB_USER
            value: "dbuser"
          - name: DB_PASSWORD
            value: "secret"
          - name: DB_NAME
            value: "testdbs"
          - name: FRONTEND
            value: "/app/public"
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-demo-public
  labels:
    app: portfolio-demo
spec:
  selector:
    app: portfolio-demo
  # type: LoadBalancer
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    name: http
